IssueComment {issueCommentUpdatedAt = GithubDate {fromGithubDate = 2013-03-22 13:35:21 UTC}, issueCommentUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/6a424256589825f609fd3477144355a0?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "yarikoptic", githubOwnerUrl = "https://api.github.com/users/yarikoptic", githubOwnerId = 39889, githubOwnerGravatarId = "6a424256589825f609fd3477144355a0"}, issueCommentUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/comments/15296723", issueCommentCreatedAt = GithubDate {fromGithubDate = 2013-03-22 13:35:21 UTC}, issueCommentBody = "Thank you @theskystalker , but my concern is that this message might be too generic -- e.g. it seems it might appear when there is a problem with a password file (e.g. incorrectly formatted entries, etc), e.g. see http://www.linux.org.ru/forum/admin/3857063 (sorry -- it is in russian but log messages give you a hint).\r\n\r\nIn case of the \"non existing username\" -- is there a previous line stating on that?  may be we could make use of multiline matching, as to be released within 0.9 series: https://github.com/fail2ban/fail2ban/pull/108", issueCommentId = 15296723}