Repo {repoSshUrl = "git@github.com:lchiquitto/fail2ban.git", repoDescription = Just "Daemon to ban hosts that cause multiple authentication errors", repoCreatedAt = GithubDate {fromGithubDate = 2011-11-21 12:14:01 UTC}, repoHtmlUrl = "https://github.com/lchiquitto/fail2ban", repoSvnUrl = "https://github.com/lchiquitto/fail2ban", repoForks = 0, repoHomepage = Just "http://www.fail2ban.org", repoFork = True, repoGitUrl = "git://github.com/lchiquitto/fail2ban.git", repoPrivate = False, repoCloneUrl = "https://github.com/lchiquitto/fail2ban.git", repoSize = 224, repoUpdatedAt = GithubDate {fromGithubDate = 2011-11-21 12:22:07 UTC}, repoWatchers = 1, repoOwner = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/dd11ae85c2dc09435724fa9bde044886?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "lchiquitto", githubOwnerUrl = "https://api.github.com/users/lchiquitto", githubOwnerId = 1205275, githubOwnerGravatarId = "dd11ae85c2dc09435724fa9bde044886"}, repoName = "fail2ban", repoLanguage = Just "Python", repoMasterBranch = Just "master", repoPushedAt = Just (GithubDate {fromGithubDate = 2011-11-21 12:22:03 UTC}), repoId = 2819623, repoUrl = "https://api.github.com/repos/lchiquitto/fail2ban", repoOpenIssues = 0, repoHasWiki = Just True, repoHasIssues = Just False, repoHasDownloads = Just True}