IssueComment {issueCommentUpdatedAt = GithubDate {fromGithubDate = 2013-03-23 21:12:24 UTC}, issueCommentUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/1c8c366f3d722f54535930017e955aa1?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "kwirk", githubOwnerUrl = "https://api.github.com/users/kwirk", githubOwnerId = 328405, githubOwnerGravatarId = "1c8c366f3d722f54535930017e955aa1"}, issueCommentUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/comments/15344897", issueCommentCreatedAt = GithubDate {fromGithubDate = 2013-03-23 21:12:24 UTC}, issueCommentBody = "Hmm... I was hoping that Travis CI would run testcases with the new configuration including python3, but for some reason it hasn't...?", issueCommentId = 15344897}