Repo {repoSshUrl = "git@github.com:ncollignon/fail2ban.git", repoDescription = Just "Daemon to ban hosts that cause multiple authentication errors", repoCreatedAt = GithubDate {fromGithubDate = 2013-04-02 17:03:22 UTC}, repoHtmlUrl = "https://github.com/ncollignon/fail2ban", repoSvnUrl = "https://github.com/ncollignon/fail2ban", repoForks = 0, repoHomepage = Just "http://www.fail2ban.org", repoFork = True, repoGitUrl = "git://github.com/ncollignon/fail2ban.git", repoPrivate = False, repoCloneUrl = "https://github.com/ncollignon/fail2ban.git", repoSize = 160, repoUpdatedAt = GithubDate {fromGithubDate = 2013-04-09 15:35:17 UTC}, repoWatchers = 0, repoOwner = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "ncollignon", githubOwnerUrl = "https://api.github.com/users/ncollignon", githubOwnerId = 4039227, githubOwnerGravatarId = "d41d8cd98f00b204e9800998ecf8427e"}, repoName = "fail2ban", repoLanguage = Just "Python", repoMasterBranch = Just "master", repoPushedAt = Just (GithubDate {fromGithubDate = 2013-04-02 17:13:04 UTC}), repoId = 9175238, repoUrl = "https://api.github.com/repos/ncollignon/fail2ban", repoOpenIssues = 0, repoHasWiki = Just False, repoHasIssues = Just False, repoHasDownloads = Just True}