IssueComment {issueCommentUpdatedAt = GithubDate {fromGithubDate = 2013-03-26 02:38:16 UTC}, issueCommentUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/6a424256589825f609fd3477144355a0?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "yarikoptic", githubOwnerUrl = "https://api.github.com/users/yarikoptic", githubOwnerId = 39889, githubOwnerGravatarId = "6a424256589825f609fd3477144355a0"}, issueCommentUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/comments/15437842", issueCommentCreatedAt = GithubDate {fromGithubDate = 2013-03-26 02:38:16 UTC}, issueCommentBody = "uff -- wasted a lot of time today but haven't pinned it down.\r\nConfusing to me point was where \"Log rotation detected\" came from in\r\nhttp://www.onerussian.com/tmp/gkrellShoot_03-25-13_222138.png\r\nbut after I added my \"fancy\" tracebacks to log messages -that I guess gave enough time to avoid this probably race condition and not sure if currently running sweep in travis would produce any interesting results.\r\n\r\nMy wild guess: in some cases (when at self.assertEqual(self.filter.failManager.getFailTotal(), 2)  0!=2) it is just that pyinotify sends event earlier than all copying of line is finished in _copy_lines_between_files, that causes the filter process partial entries. With actual rename -- not yet sure... as the last remedy -- I will move flushing into the file to the end  of and see if it helps at all ;-)\r\n \r\nIf interested:\r\nhere is the branch where I tortured the beast (some commits are worth picking later on anyways)\r\nhttps://github.com/yarikoptic/fail2ban/tree/_temp/debug_travis_failures\r\n\r\nand here you could find plenty of build logs with all kinds of failures ;-)\r\nhttps://travis-ci.org/yarikoptic/fail2ban/pull_requests", issueCommentId = 15437842}