Repo {repoSshUrl = "git@github.com:msoulard/fail2ban.git", repoDescription = Just "Daemon to ban hosts that cause multiple authentication errors", repoCreatedAt = GithubDate {fromGithubDate = 2012-12-12 22:00:57 UTC}, repoHtmlUrl = "https://github.com/msoulard/fail2ban", repoSvnUrl = "https://github.com/msoulard/fail2ban", repoForks = 0, repoHomepage = Just "http://www.fail2ban.org", repoFork = True, repoGitUrl = "git://github.com/msoulard/fail2ban.git", repoPrivate = False, repoCloneUrl = "https://github.com/msoulard/fail2ban.git", repoSize = 148, repoUpdatedAt = GithubDate {fromGithubDate = 2013-01-13 15:33:22 UTC}, repoWatchers = 0, repoOwner = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/33acf51ea0cb2496e7e30b3ec2111e50?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "msoulard", githubOwnerUrl = "https://api.github.com/users/msoulard", githubOwnerId = 3028901, githubOwnerGravatarId = "33acf51ea0cb2496e7e30b3ec2111e50"}, repoName = "fail2ban", repoLanguage = Just "Python", repoMasterBranch = Just "master", repoPushedAt = Just (GithubDate {fromGithubDate = 2012-12-13 07:33:07 UTC}), repoId = 7138414, repoUrl = "https://api.github.com/repos/msoulard/fail2ban", repoOpenIssues = 0, repoHasWiki = Just False, repoHasIssues = Just False, repoHasDownloads = Just True}