Repo {repoSshUrl = "git@github.com:mojojames/fail2ban.git", repoDescription = Just "Daemon to ban hosts that cause multiple authentication errors", repoCreatedAt = GithubDate {fromGithubDate = 2013-04-08 12:47:09 UTC}, repoHtmlUrl = "https://github.com/mojojames/fail2ban", repoSvnUrl = "https://github.com/mojojames/fail2ban", repoForks = 0, repoHomepage = Just "http://www.fail2ban.org", repoFork = True, repoGitUrl = "git://github.com/mojojames/fail2ban.git", repoPrivate = False, repoCloneUrl = "https://github.com/mojojames/fail2ban.git", repoSize = 152, repoUpdatedAt = GithubDate {fromGithubDate = 2013-04-08 13:03:39 UTC}, repoWatchers = 0, repoOwner = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/d97c8a3f00e28c2b5810c6b153893698?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "mojojames", githubOwnerUrl = "https://api.github.com/users/mojojames", githubOwnerId = 3034809, githubOwnerGravatarId = "d97c8a3f00e28c2b5810c6b153893698"}, repoName = "fail2ban", repoLanguage = Just "Python", repoMasterBranch = Just "master", repoPushedAt = Just (GithubDate {fromGithubDate = 2013-04-08 13:03:38 UTC}), repoId = 9296309, repoUrl = "https://api.github.com/repos/mojojames/fail2ban", repoOpenIssues = 0, repoHasWiki = Just False, repoHasIssues = Just False, repoHasDownloads = Just True}