Repo {repoSshUrl = "git@github.com:opoplawski/fail2ban.git", repoDescription = Just "Daemon to ban hosts that cause multiple authentication errors", repoCreatedAt = GithubDate {fromGithubDate = 2013-01-18 21:41:26 UTC}, repoHtmlUrl = "https://github.com/opoplawski/fail2ban", repoSvnUrl = "https://github.com/opoplawski/fail2ban", repoForks = 0, repoHomepage = Just "http://www.fail2ban.org", repoFork = True, repoGitUrl = "git://github.com/opoplawski/fail2ban.git", repoPrivate = False, repoCloneUrl = "https://github.com/opoplawski/fail2ban.git", repoSize = 180, repoUpdatedAt = GithubDate {fromGithubDate = 2013-01-25 16:42:06 UTC}, repoWatchers = 0, repoOwner = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/08b43f6823f1a63c7d0ae03a16b4aa6b?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "opoplawski", githubOwnerUrl = "https://api.github.com/users/opoplawski", githubOwnerId = 814662, githubOwnerGravatarId = "08b43f6823f1a63c7d0ae03a16b4aa6b"}, repoName = "fail2ban", repoLanguage = Just "Python", repoMasterBranch = Just "master", repoPushedAt = Just (GithubDate {fromGithubDate = 2013-01-18 21:44:49 UTC}), repoId = 7694947, repoUrl = "https://api.github.com/repos/opoplawski/fail2ban", repoOpenIssues = 0, repoHasWiki = Just False, repoHasIssues = Just False, repoHasDownloads = Just True}