IssueComment {issueCommentUpdatedAt = GithubDate {fromGithubDate = 2013-01-27 20:35:43 UTC}, issueCommentUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/35cb0a6a6d7bbaa753010484975c95b4?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "bluephoenix47", githubOwnerUrl = "https://api.github.com/users/bluephoenix47", githubOwnerId = 1133598, githubOwnerGravatarId = "35cb0a6a6d7bbaa753010484975c95b4"}, issueCommentUrl = "https://api.github.com/repos/fail2ban/fail2ban/issues/comments/12760972", issueCommentCreatedAt = GithubDate {fromGithubDate = 2013-01-27 20:35:43 UTC}, issueCommentBody = "Well I certainly can't figure this out. I run the test cases with -l debug, but these logs don't mean much to me. When I check journalctl, I do see some lines inserted by the journal tests.\r\n\r\nDebug log of testcases: http://sprunge.us/fNIe\r\nOutput from testcases: http://sprunge.us/NfBi\r\n\r\nBy the way, on arch pyinotify is under python2-pyinotify, and those tests seem to work fine. \r\n", issueCommentId = 12760972}