Repo {repoSshUrl = "git@github.com:loveshell/fail2ban.git", repoDescription = Just "Daemon to ban hosts that cause multiple authentication errors", repoCreatedAt = GithubDate {fromGithubDate = 2013-01-12 05:17:34 UTC}, repoHtmlUrl = "https://github.com/loveshell/fail2ban", repoSvnUrl = "https://github.com/loveshell/fail2ban", repoForks = 0, repoHomepage = Just "http://www.fail2ban.org", repoFork = True, repoGitUrl = "git://github.com/loveshell/fail2ban.git", repoPrivate = False, repoCloneUrl = "https://github.com/loveshell/fail2ban.git", repoSize = 108, repoUpdatedAt = GithubDate {fromGithubDate = 2013-01-14 02:10:49 UTC}, repoWatchers = 0, repoOwner = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/a325fb0127fce509be0b5a93e7dec913?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "loveshell", githubOwnerUrl = "https://api.github.com/users/loveshell", githubOwnerId = 1836888, githubOwnerGravatarId = "a325fb0127fce509be0b5a93e7dec913"}, repoName = "fail2ban", repoLanguage = Just "Python", repoMasterBranch = Just "master", repoPushedAt = Just (GithubDate {fromGithubDate = 2013-01-04 20:23:21 UTC}), repoId = 7571914, repoUrl = "https://api.github.com/repos/loveshell/fail2ban", repoOpenIssues = 0, repoHasWiki = Just False, repoHasIssues = Just False, repoHasDownloads = Just True}